//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginInfo
    {
        public int CustomerId { get; set; }
        public string UN { get; set; }
        public string Pwd { get; set; }
        public Nullable<int> isAdmin { get; set; }
    }
}
