//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Purchase_History
    {
        public int PID { get; set; }
        public int SID { get; set; }
        public string Product { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string url { get; set; }
        public string Description { get; set; }
        public int TotalAmount { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> Purchase_Date { get; set; }
        public Nullable<int> Quantity { get; set; }
    }
}
